- name: Install nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    state: present
    cache_valid_time: 3600

- name: Make sure a service unit is running
  become: true
  ansible.builtin.systemd_service:
    state: started
    name: nginx

- name: "Create/update nginx config"
  become: true
  ansible.builtin.file:
    src: ./nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0644"

- name: "Create/update default site"
  become: true
  ansible.builtin.file:
    src: ./default
    dest: /etc/nginx/sites-enabled/default
    owner: root
    group: root
    mode: "0644"
