---
- name: Run diplodoc roles on diplodoc-server
  hosts: diplodoc-server
  roles:
  - role: nginx-default

  - role: diplodoc-nginx
    diplodoc_config: "{{ role_path }}/files/diplodoc.yaml"

  - role: diplodoc-publish
    diplodoc_config: "{{ role_path }}/files/diplodoc.yaml"
