- name: "Read variables from the configuration file"
  ansible.builtin.include_vars:
    file: "{{ diplodoc_config }}"

- name: "Sync current docs with docs on server"
  become: true
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/../html/linux_onboarding"
    dest: "/var/www/html/linux_onboarding"
    delete: true
