- name: "Read variables from the configuration file"
  ansible.builtin.include_vars:
    file: "{{ diplodoc_config }}"

- name: Find out playbook's path
  shell: pwd
  register: playbook_path_output
- debug: var=playbook_path_output.stdout

- name: "Sync current docs with docs on server"
  become: true
  ansible.posix.synchronize:
    src: "{{ playbook_dir }}/../html/{{ item.href }}"
    dest: "/var/www/html/{{ item.href }}"
    delete: true
  loop: "{{ diplodoc_projects }}"
