- name: "Read variables from the configuration file"
  ansible.builtin.include_vars:
    file: "{{ diplodoc_config }}"

# - name: "Create/update nginx config"
#   ansible.builtin.template:
#     src: nginx.conf.j2
#     dest: /etc/nginx/nginx.conf
#     owner: root
#     group: root
#     mode: '0755'

- name: "Create/update index.html"
  become: true
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/index.html
    owner: root
    group: root
    mode: '0755'
