name: diplodoc-publish
on:
  push:
    branches:
      - main
jobs:
  diplodoc-publish:
    name: diplodoc-publish
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repo
       uses: actions/checkout@v4

     - uses: actions/setup-node@v4
       with:
         node-version: 20
     - run: npm i @diplodoc/cli -g
     - run: cd ./docs && ./gendocs.sh

     - name: Run playbook
       uses: dawidd6/action-ansible-playbook@v2
       with:
    # Required, playbook filepath
         playbook: run.yaml
    # Optional, directory where playbooks live
         directory: ./docs/ansible
    # Optional, ansible configuration file content (ansible.cfg)
         key: ${{secrets.SSH_PRIVATE_KEY}}
         options: |
          --inventory hosts
